### ISSUE TITLE
array provided by @children can't be bound

### ISSUE THREAD

**Issue by mbroadst** [aurelia/binding#384]
relevant code: https://github.com/aurelia/skeleton-navigation/compare/master...mbroadst:colspan-binding-breakage?expand=1

The code above is a minimal example of something I do in my codebase that has worked for quite some time. Something recently changed that breaks binding to `colspan` (specifically in this case binding the `length` of a `@children` variable to `colspan`). I'm having incredible difficulty tracking this down, so any help would be appreciated!

**Comment by mbroadst** [comment]
What's particularly strange in this case is that I'm able to use the `columns` variable (provided by `@children`) as part of a `repeat.for` absolutely fine, but when I try to bind the `length` of that variable to `colspan` (or even just render it directly, as can be seen at the bottom of `test.html`) it's as if the variable is undefined

**Comment by mbroadst** [comment]
Using the new aurelia chrome extension it appears as if `columns` is `undefined`, which confirms my suspicion.. but now I'm even more turned around 😄

**Comment by mbroadst** [comment]
This seems to be solved by initializing the variable. I'm pretty sure this is a breaking change, so hopefully this helps someone in the future. Specifically I had to change:
```
@children('column') columns;
```

to:
```
@children('column') columns = [];
```

**Comment by EisenbergEffect** [comment]
@jdanyow Seems we had a couple of regressions in binding. This and one other issue I saw. Any ideas what the cause could be? It would be great if we could fix. I can get a patch out as soon as you have something.

**Comment by jdanyow** [comment]
Some of the linting changes swapped `==` with `===` in a few spots.  Definitely good changes @mbroadst (I'm not complaining) but caused https://github.com/aurelia/binding/issues/377 because we didn't have test coverage for autoconvertadd at the time.

This could be the same sort of thing.  @mbroadst if you swap the current binding release (1.0.0-beta.1.3.2) with 1.0.0-beta.1.3.1 does it work? Also, if you pull down master, build and manually update is the issue resolved (eg is it resolved by fixes for #377)?

**Comment by mbroadst** [comment]
@jdanyow doh, stupid mistakes committed on my part sorry for that.

I've tested both lowering to `1.3.1` and building from master, and neither solve the problem. What's even stranger is that the updated `rjs-bundle` we've been using for the gist.run's does _not_ express this issue: https://gist.run/?id=4bf406ab1ddb67b466d4d95cb2b98f1f.  So I'm a bit turned around here.

**Comment by jdanyow** [comment]
@mbroadst if you set a conditional breakpoint in the [`getContextFor`](https://github.com/aurelia/binding/blob/master/src/scope.js#L20) function with the following condition: `name === 'children'`... does it find the object instance you'd expect?

**Comment by mbroadst** [comment]
@jdanyow adding that conditional breakpoint (wow what a nice feature to learn about, I feel like I've been missing that my whole life) didn't result in any new behavior, read: problem still exists, breakpoint was never triggered

**Comment by EisenbergEffect** [comment]
Closing this. I believe it was recently fixed (a bug in the child observation code).
